spring.application.name=spring-ecommerce
spring.datasource.url=jdbc:h2:mem:database
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.h2.console.enabled=true
spring.sql.init.mode=always
security.jwt.token.secret-key=${JWT_SECRET}
security.jwt.token.expire-length=${JWT_TIME}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false